configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://aws-0-ca-central-1.pooler.supabase.com/postgres?user=postgres.vgspqmfheuadwkuvcwvc&password=gB6Swct8wh88eaTH
